### ISSUE TITLE
set int64 gives a wrong value

### ISSUE THREAD

**Issue by Coldzer0** [BeRo1985/besen#15]
Hello BeRo
while i'm testing setting large values like
18374966859414961920

i test with

>var x = 18374966859414961920
undefined
>x
18374966859414962000
>

i try to follow the code and i think the problem is here

DoFastShortest() in BESENNumberUtils

i try to fix but i can't

can you please check it if you have time

thanks

**Comment by Coldzer0** [comment]
i think there's no problem with your code
i'm sorry for judge so fast
i test on V8 Engine and give same result

but i don't know why or how to set to the value i want

**Comment by BeRo1985** [comment]
(Mostly) all number values at ECMAScript/JavaScript are IEEE754 64-bit Double-Precision Floating Point values, and these can hold only up to 53-bit integer values lossless. See http://2ality.com/2012/04/number-encoding.html and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER and so on. So it's here by language-design.

**Comment by Coldzer0** [comment]
@BeRo1985  do you plan to update to ES6 ? or update the current project !
