### ISSUE TITLE
TBESEN.RegisterNativeObject - fault with freepascal

### ISSUE THREAD

**Issue by JernejL** [BeRo1985/besen#17]
No issues with RegisterNativeObject in delphi, however in freepascal 3.0.4, this function fails with error 219 (Invalid typecast) at line TBESENObject(v.Obj):=AClass.Create(self,ObjectPrototype); 
 
Looks like RTL problem?

**Comment by Coldzer0** [comment]
i'm using Besen with fpc 3.0.4 and it works fine for me 

how do u use "RegisterNativeObject" if you can provide code so we can check it.

the "RegisterNativeObject" has 2 params the name of object and second one is TBESENNativeObject

you can check my code here
https://github.com/Coldzer0/Cmulator/blob/master/Core/jsplugins_bengine.pas

**Comment by BeRo1985** [comment]
It looks more like a bug in FPC itself and not in BESEN, because TBESENNativeObjectClass (what AClass is) is "class of TBESENNativeObject" and TBESENNativeObject is derived from ToBESENObjectFunction and TBESENObjectFunction is derived from TBESENObject. 

At least with FPC 3.1.1 it works for me, so I close this issue now.

**Comment by BeRo1985** [comment]
And I think, you should update from FPC 3.0.4 to a newer FPC version, no matter if stable or dev-version :-)

**Comment by BeRo1985** [comment]
Or you're misusing RegisterNativeObject with a class, which is not derived from TBESENNativeObject?

**Comment by JernejL** [comment]
I'll give it a try with newer fpc, i haven't tried updating fpc without that being part of lazarus tho, so that might turn to be slightly challenging for me. 
 
I was using RegisterNativeObject like this: 
 
`BesenInst.RegisterNativeObject('Vehicle', TVehicleInterface); `
 
This is the class: 
 
`TVehicleInterface = class(TBESENNativeObject)
	protected
		procedure ConstructObject(const ThisArgument: TBESENValue; Arguments: PPBESENValues; CountArguments: integer); Override;
	public
		constructor Create(AInstance: TObject; APrototype: TBESENObject=nil; AHasPrototypeProperty: longbool=false); Overload;
	private
	    eh: TEntityHandle;
	published

end;`
 
Note that this does work indeed OK in delphi 7, or could my compiler directives have something to do with this breaking?
