### ISSUE TITLE
just a heads up about the other problem..

### ISSUE THREAD

**Issue by JernejL** [BeRo1985/besen#18]
Regarding https://github.com/BeRo1985/besen/issues/17 since ticket is closed, i assume you didn't get notification about the final solution and cause of the problem: 
 

I did some homework and determined that this is caused by verify method calls -CR option being on (not to be confused with -Cr / range checks)

-CR
Generate checks when calling methods to verify if the virtual method table for that object is valid.

If this is used, RegisterNativeObject fails as described, probably will also fail in fpc 3.1.1.

**Comment by BeRo1985** [comment]
I get notifications even on closed issues. Then avoid -CR at least for these units in the meantime?
