### ISSUE TITLE
var a=0; reports  undefined error

### ISSUE THREAD

**Issue by kaisatec** [BeRo1985/besen#2]
Thanks for your great job

there is an issue, in shell I input

       var a=0; 

it reports  undefined error

I have to remove 'var', then it works

Is it not standard javascript?

Thanks

Z Wang

**Comment by BeRo1985** [comment]
This is no error. "var a=0;" returns just a undefined value. 

Test it also in the javascript consoles of Firefox and Chrome, you will see, that it is no error. :)
