### ISSUE TITLE
Parser error

### ISSUE THREAD

**Issue by noname00-pas** [BeRo1985/besen#4]
Open https://raw.githubusercontent.com/mozilla/task.js/master/lib/task.js in Besen IDE then click Run
Result:

![untitled](https://cloud.githubusercontent.com/assets/7973218/10627369/c377083a-77e2-11e5-9e79-9bd785c32ae4.png)

**Comment by BeRo1985** [comment]
The "const" keyword on line 119 isn't a part of the ECMAScript 5th edition, so it's not an bug. And BESEN will be updated to ECMAScript 6 (which has the "const" and "let" keywords) only later, when I've have more time for BESEN again.
