### ISSUE TITLE
Not build In Delphi 10 Seattle

### ISSUE THREAD

**Issue by JhonnyUmpire** [BeRo1985/besen#7]
Please add in BESEN.inc 
 {$ifdef ver290}
  {$define DelphiXE8}
  {$define DelphiXE7}
  {$define DelphiXEAndUp}
  {$define DelphiXE2AndUp}
  {$define DelphiXE3AndUp}
  {$define DelphiXE4AndUp}
  {$define DelphiXE5AndUp}
  {$define DelphiXE6AndUp}
  {$define DelphiXE7AndUp}
  {$define DelphiXE8AndUp}
  {$define Delphi2009AndUp}
 {$endif}
 {$ifdef ver300}
  {$define DelphiXE9}
  {$define DelphiXE8}
  {$define DelphiXE7}
  {$define DelphiXEAndUp}
  {$define DelphiXE2AndUp}
  {$define DelphiXE3AndUp}
  {$define DelphiXE4AndUp}
  {$define DelphiXE5AndUp}
  {$define DelphiXE6AndUp}
  {$define DelphiXE7AndUp}
  {$define DelphiXE8AndUp}
  {$define DelphiXE9AndUp}
  {$define Delphi2009AndUp}
 {$endif}

**Comment by imekon** [comment]
Here's the extra for Berlin:

    {$ifdef ver310}
      {$define DelphiXE7}
      {$define DelphiXEAndUp}
      {$define DelphiXE2AndUp}
      {$define DelphiXE3AndUp}
      {$define DelphiXE4AndUp}
      {$define DelphiXE5AndUp}
      {$define DelphiXE6AndUp}
      {$define DelphiXE7AndUp}
      {$define DelphiXE8AndUp}
      {$define DelphiXE9AndUp}
      {$define Delphi2009AndUp}
      {$define Delphi2010SeattleAndUp}
      {$define Delphi2010BerlinAndUp}
    {$endif}

**Comment by BeRo1985** [comment]
Fixed
